pool:
  name: Hosted VS2017
  demands: npm

steps:
- task: Npm@1
  displayName: 'npm install'
  inputs:
    command: install
    verbose: false

- task: Npm@1
  displayName: 'npm lint'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run lint'
  enabled: false

- task: Npm@1
  displayName: 'npm build'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run build'

- task: Npm@1
  displayName: 'npm run export'
  inputs:
    command: custom
    verbose: false
    customCommand: 'run export'

- task: CopyFiles@2
  displayName: 'Copy build files to artifacts staging directory'
  inputs:
    Contents: |
     .next-exported/**/*
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.ArtifactStagingDirectory)'
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

